### PR TITLE
Add textfields to alert

### PR DESCRIPTION
**Pull request by akwilliamson**
This adds simple convenience methods for adding textfields to a controller. Users can opt for a default textfield, optionally include placeholder text, or optionally configure the textfield for secure text entry.

### CODE REVIEW

**Comment by akwilliamson** [comment]
I'm not familiar with CircleCI or why it says "checks have failed" but if it's something I can fix please let me know and I'll take care of it!

**Comment by eriksargent** [comment]
Thanks for submitting the PR. It looks like circle failed to run the tests because I added the config file for Circle CI after you made your fork. Will you try merging my changes from master into your branch? That should take care of that. Will you also mark the addTextField method in LKAlertController as internal instead public because it doesn't apply to ActionSheet, so that will prevent it from being accessible from ActionSheet. You could also add some instructions in the README if you'd like

**Comment by eriksargent** [comment]
Please also make your functions return self so they can be stacked like the add action/show functions

**Comment by eriksargent** [comment]
Fixes #5

**Comment by akwilliamson** [comment]
All set I think, I'll update the README with some instructions as soon as it's merged.

**Comment by eriksargent** [comment]
Sweet, looks good. We probably also need a way to get the value out of the text field... I'll create a separate issue for that.

**Pull request merged**
