### PR TITLE
Update README.md for using text fields in alerts

### PR DESCRIPTION
**Pull request by akwilliamson**
This includes instructions for variations on text field initialization and chaining text fields with other Alert methods. Note: Don't merge this PR until https://github.com/lightningkite/LKAlertController/pull/18 is merged.

### CODE REVIEW

**Comment by eriksargent** [comment]
Fixes #15

**Comment by akwilliamson** [comment]
I'm thinking eventually down the road (not necessarily at the moment) the README might be further organized by extrapolating the `Alert` and `ActionSheet` classes into their own exclusive sections as the LKAlertController functionality continues to evolve uniquely to each class.

Something like:
...

##### LKAlertController
- Shared functionality

##### Alert
- Functionality unique to Alert

##### ActionSheet
- Functionality unique to ActionSheet

...

We can open a separate PR at the point where there is enough unique content to differentiate the two classes. What do you think?

**Comment by akwilliamson** [comment]
I'm learning a lot. Thanks for letting me contribute!

**Comment by eriksargent** [comment]
I like that idea. I'll start working on that. Thanks for helping!

**Pull request merged**
