### PR TITLE
Carthage Support

### PR DESCRIPTION
**Pull request by hardikdevios**
1. Pull it.
2. Bump the Version (New Tag)
3. Add this in README.md
   `github "lightningkite/LKAlertController"`
4. Cheers buddy

### CODE REVIEW

**Comment by eriksargent** [comment]
Your changes have broken the continuous integration. Please mark the testing scheme as shared, and change the name of the scheme in the `circle.yml` file to match the new target name

**Comment by eriksargent** [comment]
And if you'd add carthage installation instructions to the README that's be awesome

**Comment by hardikdevios** [comment]
Oops sorry i have made mistake fixing the shared schema issue

**Comment by hardikdevios** [comment]
Updated README.md with Carthage Detail and Shared schema of yours are back. Happy Coding :)

**Comment by eriksargent** [comment]
Thanks for the PR!

**Comment by hardikdevios** [comment]
All yours Cheers 👍

**Comment by eriksargent** [comment]
A tag has been pushed

**Comment by hardikdevios** [comment]
I guess you have change something in schema i Got error like this

```
LKAlertController/Example/LKAlertController.xcworkspace -scheme Pods-LKAlertController_Tests-LKAlertController -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme Pods-LKAlertController_Tests-LKAlertController is not currently configured for the build action.
```

**Comment by eriksargent** [comment]
Okay I'll investigate

**Comment by eriksargent** [comment]
Ahh...Cocoapods removed the changes. I'll reverse that

**Comment by eriksargent** [comment]
Okay try that

**Comment by hardikdevios** [comment]
Done buddy cheers 👍

**Pull request merged**
